kind: pipeline
type: kubernetes
name: default

clone:
  disable: true

steps:
  - name: clone
    image: alpine/git
    commands:
    - git clone https://github.com/prabhatsharma/sample-microservice .
    - git checkout $DRONE_COMMIT

  - name: build
    image: golang
    commands: 
    - CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o main

  - name: publish  
    image: plugins/ecr
    settings:
      repo: sample-microservice
      registry: 566178068807.dkr.ecr.us-west-2.amazonaws.com

  - name: greeting
    image: alpine
    commands:
    - echo hello
    - echo world
    